name: otp_autofill_demo
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  otp_autofill: ^2.1.0


dev_dependencies:
  dart_code_metrics: ^4.8.1
  flutter_test:
    sdk: flutter

  surf_lint_rules: ^1.4.1

flutter:

  uses-material-design: true